genovese/genovese/urls.py
from django.contrib import admin
from django.urls import include, path
from login.views import frontpage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('nutrients/', include('nutrients.urls'))
]

genovese/login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

genovese/nutrients/urls.py
from django.urls import path
from .views import TestView

app_name = 'nutrients'

urlpatterns = [
    path('test/',  TestView.as_view(), name='test')
]

genovese/login/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):

    account_id = models.CharField(
        verbose_name=_("account_id"),
        unique=True,
        max_length=10
    )
    email = models.EmailField(
        verbose_name=_("email"),
        unique=True
    )
    first_name = models.CharField(
        verbose_name=_("first_name"),
        max_length=150,
        null=True,
        blank=False
    )
    last_name = models.CharField(
        verbose_name=_("last_name"),
        max_length=150,
        null=True,
        blank=False
    )
    birth_date = models.DateField(
        verbose_name=_("birth_date"),
        blank=True,
        null=True
    )
    is_superuser = models.BooleanField(
        verbose_name=_("is_superuer"),
        default=False
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.account_id

genovese/nutrients/models.py
from django.db import models

# Create your models here.

genovese/login/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
            "email",
            "first_name",
            "last_name",
            "birth_date",
        )

class LoginFrom(AuthenticationForm):
    class Meta:
        model = User

genovese/login/views.py
from django.shortcuts import render

from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.urls import reverse_lazy
from .forms import SignUpForm, LoginFrom
# Create your views here.

def frontpage(request):
  return render(request, "login/frontpage.html")


class IndexView(TemplateView):
    """ ホームビュー """
    template_name = "index.html"


class SignupView(CreateView):
    """ ユーザー登録用ビュー """
    form_class = SignUpForm # 作成した登録用フォームを設定
    template_name = "login/signup.html" 
    success_url = reverse_lazy("login:index") # ユーザー作成後のリダイレクト先ページ

    def form_valid(self, form):
        # ユーザー作成後にそのままログイン状態にする設定
        response = super().form_valid(form)
        account_id = form.cleaned_data.get("account_id")
        password = form.cleaned_data.get("password1")
        user = authenticate(account_id=account_id, password=password)
        login(self.request, user)
        return response

class LoginView(BaseLoginView):
    form_class = LoginFrom
    template_name = "login/login.html"

# LogoutViewを追加
class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("login:index")

genovese/nutrients/views.py
# from django.shortcuts import render
from django.views import generic

# Create your views here.

class TestView(generic.TemplateView):
    template_name = 'test.html'

genovese/recipe_app/views.py
from django.shortcuts import render

# Create your views here.

#viewの書き方はclassを使うのもおすすめ

genovese/login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Djangoブログ</title>
  <!-- Bootstrap CSS CDN Link -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>
<body>
  {% block content %} {% endblock %}
</body>
</html>

genovese/login/templates/login/login.html
<form action="" method="POST">
  {% csrf_token %}
  {% for field in form %}
</form>

genovese/login/templates/login/post_detail.html
{% extends "login/base.html" %} {% block content %}

<h2>{{post.title}}</h2>
<p>posted at {{post.posted_date}}</p>
<p>{{post.intro}}</p>
<p>{{post.body}}</p>

<!-- コメントされたものを表示 -->
<hr>
<h2>コメント</h2>
{% for comment in post.comments.all %}
<p>
  <strong>
    {{comment.name}}
    <small>{{comment.posted_date}}</small>
    <small>{{comment.body}}</small>
  </strong>
</p>

{% empty %}
<p>コメントはまだありません</p>
{% endfor %}
<hr>
<!-- コメント投稿エリア -->
<h2 class="subtitle">コメントを追加</h2>
<form action="." method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button class=""button is-danger>送信</button>

</form>


<a href="/login">戻る</a>


{% endblock %}

genovese/nutrients/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>TEST PAGE</h1>
    
</body>
</html>

genovese/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap5のCDNを設定 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <title>Account</title>
</head>

<body>
  <div class="container mx-auto text-center">
    {% block title %}
    {% endblock %}
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

genovese/templates/index.html
{% extends 'base.html' %}

{% block title %}
{% if user.is_authenticated %}
<div class="h1">MyPage</div>
{% else %}
<div class="h1">Main</div>
{% endif %}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="h2">Welcome {{ user.first_name }} {{ user.last_name }}</div>
<a href="{% url 'login:logout' %}" class="btn btn-primary">Logout</a>
{% else %}
<a href="{% url 'login:signup' %}" class="btn btn-primary">Signup</a>
<a href="{% url 'login:login' %}" class="btn btn-primary">Login</a>
{% endif %}
{% endblock %}


genovese/templates/login/login.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Login</div>
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'login:index' %}" class="btn btn-secondary">Back</a>
    </div>
</form>
{% endblock %}

genovese/templates/login/signup.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Create account</div>
{% endblock %}

{% block content %}
<div>
  <br>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
      <button type="submit" class="btn btn-primary">Create</button>
      <a href="{% url 'login:index' %}" class="btn btn-secondary">Back</a>
    </div>
  </form>
</div>
{% endblock %}